name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  ENV_WASMEDGE_INST: https://raw.githubusercontent.com/WasmEdge/WasmEdge/master/utils/install.sh

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: install wasmedge
      run: |
        curl --silent --show-error --location $ENV_WASMEDGE_INST
        bash install.sh
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
